microservice-chart:
  namespace: "nodo"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-nodo-verifyko-aux
    tag: "0.2.0"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weuprod.nodo.internal.platform.pagopa.it"
    path: /pagopa-nodo-verifyko-aux(/|$)(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.25"
    limits:
      memory: "512Mi"
      cpu: "0.25"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 1
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    WEBSITE_SITE_NAME: 'pagopanodoverifykoaux' # required to show cloud role name in application insights
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-connection-string'
    APPLICATIONINSIGHTS_ROLE_NAME: "pagopa-nodo-verifyko-aux"
    ENV: 'aks-dev'
    APP_LOGGING_LEVEL: 'DEBUG'
    DEFAULT_LOGGING_LEVEL: 'INFO'
    CORS_CONFIGURATION: '{"origins": ["*"], "methods": ["*"]}'
    VERIFYKO_COLDSTORAGE_TABLE: 'events'
    VERIFYKO_COLDSTORAGE_BLOBCONTAINER: 'payload'
    VERIFYKO_HOTSTORAGE_DATABASE: 'nodo_verifyko'
    VERIFYKO_HOTSTORAGE_ENABLEQUERYMETRICS: 'false'
    OTEL_SERVICE_NAME: "pagopa-nodo-verifyko-aux"
    OTEL_RESOURCE_ATTRIBUTES: "service.environment=prod"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
  envSecret:
    # required
    APPLICATIONINSIGHTS_CONNECTION_STRING: "azure-insight-connection-string"
    OTEL_EXPORTER_OTLP_HEADERS: "elastic-apm-secret-token"
    VERIFYKO_COLDSTORAGE_CONNECTION: "verifyko-tablestorage-connection-string"
    VERIFYKO_HOTSTORAGE_URI: "verifyko-datastore-cosmos-uri"
    VERIFYKO_HOTSTORAGE_KEY: "cosmos-verifyko-account-key"
  keyvault:
    name: "pagopa-p-nodo-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
